### ISSUE TITLE
Feature request: Optionally show full component path in the search results

### ISSUE THREAD

**Issue by Nytra** [Banane9/NeosComponentAttacherSearch#2]
I think this would make it easier to actually learn where specific components are located instead of just relying on the search every time.

For example, if you are searching for "`ValueField`", instead of just showing "`ValueField<T>`" in the list, it would show something like "`Data > ValueField<T>`" to show you exactly which categories the component belongs to.

**Comment by Nytra** [comment]
Thanks!

**Comment by Nytra** [comment]
I'm trying to build this and I'm getting these errors which I don't know how to resolve. Do you have any ideas?

```
1>C:\...\NeosComponentAttacherSearch\ComponentAttacherSearch\ComponentAttacherPatch.cs(140,56,140,63): error CS0122: 'ComponentAttacher._uiRoot' is inaccessible due to its protection level
1>C:\...\NeosComponentAttacherSearch\ComponentAttacherSearch\ComponentAttacherPatch.cs(164,44,164,51): error CS0122: 'ComponentAttacher._uiRoot' is inaccessible due to its protection level
1>C:\...\NeosComponentAttacherSearch\ComponentAttacherSearch\ComponentAttacherPatch.cs(191,66,191,73): error CS1061: 'ComponentAttacher' does not contain a definition for 'BuildUI' and no accessible extension method 'BuildUI' accepting a first argument of type 'ComponentAttacher' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by Banane9** [comment]
You need to build against an assembly where everything has been made public.

You can use this for example:  
https://github.com/Banane9/PublifyReferences
